# Generated by Django 2.0.6 on 2018-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montesory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=1000)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
    ]
