# Generated by Django 2.0.6 on 2018-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montesory', '0005_auto_20180616_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='adr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='code_postale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
