# Generated by Django 2.0.6 on 2018-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montesory', '0006_auto_20180622_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
