# Generated by Django 2.0.6 on 2018-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montesory', '0007_auto_20180624_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='messages2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=2555)),
            ],
        ),
    ]
