# Generated by Django 2.0.6 on 2018-06-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montesory', '0008_messages1_messages2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages1',
            new_name='MessageA',
        ),
        migrations.RenameModel(
            old_name='messages2',
            new_name='MessageB',
        ),
    ]
