# Generated by Django 2.0.6 on 2018-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montesory', '0009_auto_20180625_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagea',
            name='is_visted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageb',
            name='is_visted',
            field=models.BooleanField(default=False),
        ),
    ]
